[global]
excludes = [".nitro/**", ".output/**", "dist/**"]

[formatter.prettier]
command = "pnpm"
options = ["exec", "prettier", "--write"]
includes = [
  "*.js",
  "*.mjs",
  "*.cjs",
  "*.ts",
  "*.json",
  "*.md",
  "*.yaml",
  "*.yml",
  "*.css",
  "*.html",
]
